---

resources:
- name: java-buildpack
  type: git
  source:
    uri: {{java-buildpack-git-uri}}
    private_key: {{github-private-key}}

- name: java-buildpack-latest
  type: docker-image
  source:
    repository: splatform/java-buildpack
    username: {{docker-username}}
    password: {{docker-password}}
    email: cf-ci-bot@suse.de

- name: ubuntu-trusty
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

- name: s3.buildpack-rc-offline
  type: s3
  source:
    bucket: {{java-buildpack-s3-bucket}}
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    regexp: buildpack-release-candidates/java/java-buildpack-offline-v(.*).zip

- name: s3.buildpack-rc-online
  type: s3
  source:
    bucket: {{java-buildpack-s3-bucket}}
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    regexp: buildpack-release-candidates/java/java-buildpack-v(.*).zip

groups:
- name: docker
  jobs:
  - docker-image
- name: java-buildpack
  jobs:
  - java-unit-2.2
  - java-unit-2.3
  - java-unit-2.4
  - java-package-online
  - java-package-offline

jobs:
- name: docker-image
  plan:
  - aggregate:
    - resource: java-buildpack
      get: docker-image
      trigger: true
    - get: ubuntu-trusty
      trigger: true
  - do:
    - put: java-buildpack-latest
      params:
        build: docker-image/ci/docker-image
- name: java-unit-2.2
  plan:
  - aggregate:
    - get: java-buildpack
      trigger: true
  - do:
    - task: unit-test
      file: java-buildpack/ci/unit-test.yml
      params:
        RBENV_VERSION: 2.2.7
- name: java-unit-2.3
  plan:
  - aggregate:
    - get: java-buildpack
      trigger: true
  - do:
    - task: unit-test
      file: java-buildpack/ci/unit-test.yml
      params:
        RBENV_VERSION: 2.3.4
- name: java-unit-2.4
  plan:
  - aggregate:
    - get: java-buildpack
      trigger: true
  - do:
    - task: unit-test
      file: java-buildpack/ci/unit-test.yml
      params:
        RBENV_VERSION: 2.4.1
- name: java-package-online
  plan:
  - aggregate:
    - get: java-buildpack
      trigger: true
      passed:
      - java-unit-2.2
      - java-unit-2.3
      - java-unit-2.4
  - do:
    - task: package-test
      file: java-buildpack/ci/package-test.yml
    - task: checksum-package
      file: java-buildpack/ci/checksum-package.yml
    - put: s3.buildpack-rc-online
      params:
        file: package-tagged/java-buildpack-v3.17-*.zip
        acl: public-read
- name: java-package-offline
  plan:
  - aggregate:
    - get: java-buildpack
      trigger: true
      passed:
      - java-unit-2.2
      - java-unit-2.3
      - java-unit-2.4
  - do:
    - task: package-test
      file: java-buildpack/ci/package-test.yml
      params:
        OFFLINE: true
        PINNED: true
    - task: checksum-package
      file: java-buildpack/ci/checksum-package.yml
    - put: s3.buildpack-rc-offline
      params:
        file: package-tagged/java-buildpack-offline-v3.17-*.zip
        acl: public-read
